### ISSUE TITLE
Firefox: middle and right panels don't load

### ISSUE THREAD

**Issue by michaelieti** [schoolgendev/sg-map-dashboard#2]
Not entirely sure why, investigate further

**Comment by michaelieti** [comment]
Seems to be loading fine on firefox 52.0.2.  
@Schoolgen could you possibly comment with the versions that the map page isn't loading for?
![screencap of map page - firefox 52 0 2 32-bit](https://cloud.githubusercontent.com/assets/11637317/24822883/fa4ef452-1c4c-11e7-8f9d-6451668782c1.JPG)

**Comment by Schoolgen** [comment]
Was using old version of Firefox (42) - now updated to latest (52) - both map and solar dash working correctly! :-)

**Comment by Schoolgen** [comment]
Hi Michael

Thanks. I have updated Firefox and now wroking correctly. Closed that issue.
Issue with map and dash still remains with IE v11
[image: Inline image 1]
